# CustomEnchants by Peaches_MLG
Options:
# Do you want the plugin to automatically update?
# Requires MVDWUpdater
  Update: true
# Prefix of all the messages
  Prefix: '&c&lCustomEnchants &7>>'
# Gui title
  Title: '&c&lCustomEnchants'
# Do you want a gui where you can buy enchants?
  TierGUI: true
# Gui Configuration
  TierAmount: 3
# What slot do you want each tier to be in
  Tier1Slot: 12
  Tier2Slot: 14
  Tier3Slot: 16
# How much will each tier cost?
  Tier1Cost: 20
  Tier2Cost: 40
  Tier3Cost: 60
# What item do you want each Tier to be
  Tier1Item: ENCHANTED_BOOK
  Tier1Meta: 0
  Tier2Item: ENCHANTED_BOOK
  Tier2Meta: 0
  Tier3Item: ENCHANTED_BOOK
  Tier3Meta: 0
  GkitsBackgroundItem: STAINED_GLASS_PANE
  GkitsBackgroundMeta: 7
# What do you want each item to be called?
  Tier1Name: '&b&lBasic Tier'
  Tier2Name: '&5&lEpic Tier'
  Tier3Name: '&6&lLegendary Tier'
  Tier1MessageName: 'Basic Tier'
  Tier2MessageName: 'Epic Tier'
  Tier3MessageName: 'Legendary Tier'
# What do you want the lore format to be?
  Tier1LoreFormat: '&7'
  Tier2LoreFormat: '&7'
  Tier3LoreFormat: '&7'
# Do you want the item to have a glow effect?
  Tier1Glow: true
  Tier2Glow: true
  Tier3Glow: true
# Format for the cost
  TierCostFormat: '&cCost: &4&l%Cost%XP'
  EnchantCrystalItem: NETHER_STAR
  EnchantCrystalGlow: true
  EnchantCrystalLore:
  - '&7&lRight Click The Crystal to Use it'
  - '&7&l%Description%'
# How do you want the players to pay for the enchants? (XpLevels Xp Vault)
  Payment: XpLevels
# When using an infusion do you want it to call an event to all other plugins, this will be useful for plugins such as McMMO or anti grief plugins. but can also make anticheats falseban for nuke(Unless your anticheat is supported)
  UseBlockBreakEvent: true
# Format for the Crystal
  CrystalNameFormat: '&c&l&n'
  CrystalLoreFormat: '&7&l'
# What is the Maximum amount of enchants allowed on one item
  MaxEnchants: 20
# next page and previous page for the /ce list gui
  NextPage: '&a&lNext Page'
  PreviousPage: '&c&lPrevious Page'
# What do you want the amount of hearts a player gets to be, default = 20
  DefaultHearts: 20
# What should the radius be for enchants like Saviour
  AllyRadius: 10
# What Items do you want to be in each tier?
Tiers:
  Tier1:
  - SpeedI
  - JumpI
  - DecapitateI
  - VisionaryI
  - NetherSkinI
  - ReplenishI
  - LifestealI
  - AquaticI
  - HardenedI
  - JacketI
  - PenetrateI
  - EvadeI
  - EnlightenedI
  - CookI
  - CatchI
  - ThunderusBlowI
  Tier2:
  - BlazingTouchI
  - SpeedII
  - JumpII
  - MultishotI
  - InfusionI
  - IgnitionI
  - WitherI
  - HasteI
  - LifestealII
  - JacketII
  - CursedI
  - AssassinateI
  - CoinsI
  - HardenedII
  - PenetrateII
  - EvadeII
  - WingsI
  - SaviorI
  - LeaderI
  - ResistanceI
  - EnlightenedII
  - CatchII
  - FrostbiteI
  - HeadshotI
  Tier3:
  - MultishotII
  - InfusionII
  - WitherII
  - HasteII
  - JacketIII
  - InquisitiveI
  - InquisitiveII
  - CursedII
  - FrostyI
  - FlareI
  - AssassinateII
  - CoinsII
  - HardenedIII
  - PenetrateIII
  - EvadeIII
  - SaviorII
  - LeaderII
  - ResistanceII
  - EnlightenedIII
  - FrostbiteII
  - HeadshotII